services:
  - docker
dist: xenial
language: generic
matrix:
  include:
  - name: python3.6
    env: DOCKERIMAGE=python:3.6-stretch
  - name: python3.8
    env: DOCKERIMAGE=python:3.8-stretch
install:
  - docker pull $DOCKERIMAGE
script:
  - docker run -it --rm -v $(pwd):/einops/ $DOCKERIMAGE bash -c 'python /einops/test.py'
